// ═══════════════════════════════════════════════
// SUPABASE
// ═══════════════════════════════════════════════
const SUPABASE_URL  = 'https://gdlkslptehtxudfghhqh.supabase.co';
const SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkbGtzbHB0ZWh0eHVkZmdoaHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2MTY1MzIsImV4cCI6MjA5NDE5MjUzMn0.p-NfAzh1gVmuaPiRNv0kubERaGLyfWmbF2GnheExYIA';
const sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON);

// ═══════════════════════════════════════════════
// SERVER-AUTHORITATIVE RPC ADAPTER
// Generated by ChatGPT. After running supabase_server_authoritative.sql,
// important actions below call Supabase RPC instead of directly trusting browser state.
// ═══════════════════════════════════════════════
let currentBattleId = null;

async function serverRpc(name, args = {}) {
  const { data, error } = await sb.rpc(name, args);
  if (error) {
    console.error('RPC failed:', name, error);
    showToast(error.message || `Server error: ${name}`);
    throw error;
  }
  return data;
}

function applyServerPayload(payload) {
  const root = payload?.state || payload;
  const s = root?.v2 || root?.save_data?.v2 || root;
  if (!s) return;
  if (s.resources) Object.assign(resources, s.resources);
  if (s.playerXP !== undefined) playerXP = s.playerXP;
  if (s.playerLevel !== undefined) playerLevel = s.playerLevel;
  if (s.nodes) {
    RESOURCE_DEFS.forEach(r => {
      if (s.nodes[r.id]) r.tiers.forEach((_, ti) => {
        if (s.nodes[r.id][ti]) Object.assign(nodeState[r.id][ti], s.nodes[r.id][ti]);
      });
    });
  }
  if (s.research) {
    RESEARCH_DEFS.forEach(rd => {
      if (s.research[rd.id]) Object.assign(researchState[rd.id], s.research[rd.id]);
    });
    activeResearchId = null;
    RESEARCH_DEFS.forEach(rd => { if (researchState[rd.id]?.researching) activeResearchId = rd.id; });
  }
  if (s.armoryTowers) armoryTowers = s.armoryTowers;
  if (s.campCompleted) campCompletedStages = new Set(s.campCompleted);
  buildResourcesPanel();
  buildResearchPanel();
  buildInventoryPanel();
  buildCraftingPanel();
  buildCampaignMap();
  updateResourcePills();
  updatePlayerLevelUI();
}

async function refreshFromServer() {
  const payload = await serverRpc('idw_get_state');
  applyServerPayload(payload);
  return payload;
}


